### ISSUE TITLE
Substring search is slow

### ISSUE THREAD

**Issue by Boshen** [modern-js-dev/rspack-sources#46]
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/1430279/220254486-8937ac62-3aeb-4109-937e-670d6fc936ec.png">

When `devtool: "source-map"` is turned on, substring search blew up.

**Comment by IWANABETHATGUY** [comment]
Fixed by https://github.com/modern-js-dev/rspack-sources/pull/47
